[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

# Tambah timeout agar Invidious punya cukup waktu merespons
[functions."get-video-info"]
  timeout = 20

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"
